version: 2.1

# Define a job to be invoked later in a workflow.

jobs:
  lint:
    executor: go_docker
    steps:
      - checkout
      - run:
          name: Lint the Go cmd/web
          command: gofmt -d ./cmd/web
      - run:
          name: Lint the Go pkg/
          command: gofmt -d ./pkg
  unit-tests:
    executor: go_docker
    steps:
      - checkout
      - run:
          name: Run cmd/web Go unit tests
          command: go test ./cmd/web

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - lint
      # - code coverage
      - go-static-analyzer
      - unit-tests:
          requires:
            - lint
            - go-static-analyzer
      - deploy:
          requires:
            - unit-tests
          filters:
            branches:
              only:
                - main


     
