version: 2.1
orbs:
  ruby: circleci/ruby@2.6.3
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.6.3'
      - run: ruby -v
workflows: null

